config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  authenticate :user, lambda { |u| u.admin? } do
    resources :dispatches, only: :index
    mount Sidekiq::Web, at: 'sidekiq'
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        # post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        delete "sign_out", to: "sessions#destroy"
      end
      resources :messages, only: [:create]
    end
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dispatch.rb
class Dispatch < ApplicationRecord
  extend Enumerize
  belongs_to :message

  enumerize :messenger_type, in: { viber: 0, telegram: 1, whatsapp: 2 }, predicates: true, scope: true
  enumerize :status, in: { pending: 0, process: 1, sent: 2, error: 3 }, predicates: true, scope: true

  default_scope -> { order(id: :desc) }

  validates :messenger_type, :status, presence: true
  validates :phone, phone: { types: [:mobile] }
  validate :validate_send_at, on: :create
  validate :validate_phone, on: :create
  validate :validate_repeat, on: :create

  after_create_commit :send_message

  private

  def validate_phone
    if message.dispatches.to_a.select { |a| a[:messenger_type] == messenger_type && a[:phone] == phone }.length > 1
      errors.add(:phone, I18n.t('uniqueness_constraint_violated'))
    end
  end

  def validate_send_at
    if send_at && send_at <= Time.zone.now
      errors.add(:send_at, I18n.t('must_be_greater_than_the_current_time'))
    end
  end

  def validate_repeat
    check_message = Message.where(body: message.body).first
    if check_message and check_message.dispatches.where(messenger_type: messenger_type, phone: phone).count > 0
      errors.add(:phone, I18n.t('a_similar_message_using_messenger_type_has_already_been_sent_to_phone',
                                messenger_type: messenger_type,
                                phone: phone))
    end
  end

  def send_message
    SendMessageJob.set(wait_until: (send_at? ? send_at : Time.zone.now)).perform_later(self)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :dispatches, inverse_of: :message, dependent: :destroy
  accepts_nested_attributes_for :dispatches
  validates :body, presence: true
  validate :at_least_one_dispatches
  default_scope -> { order(id: :desc) }

  private

  def at_least_one_dispatches
    errors.add :base, I18n.t('must_have_at_least_one_dispatch') unless dispatches.length > 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize
  has_many :messages, dependent: :destroy
  acts_as_token_authenticatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enumerize :role, in: { user: 0, admin: 1 }, predicates: true, scope: true
end

app/controllers/api/v1/messages_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class MessagesController < ActionController::API
      # acts_as_token_authentication_handler_for User
      before_action :need_authenticate!

      def create
        @message = Message.new(message_params)
        @message.user = current_user

        if @message.save
          render json: { messages: I18n.t('message_sent_for_processing'), is_success: true,
                         data: { message: @message } }, status: :ok
        else
          render json: { messages: @message.errors.messages, is_success: false, data: {} },
                 status: :unprocessable_entity
        end
      end

      private

      def message_params
        params.permit(:body, dispatches_attributes: %i[id phone messenger_type send_at])
      end

      def need_authenticate!
        unless user_signed_in?
          render json: { messages: I18n.t('user_unauthorized'), is_success: false, data: {} },
                 status: :unauthorized
        end
      end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class SessionsController < Devise::SessionsController
      before_action :load_user, only: :create
      skip_before_action :verify_authenticity_token

      def create
        if @user.valid_password?(sign_in_params[:password])
          sign_in 'user', @user
          render json: { messages: I18n.t('signed_in_successfully'), is_success: true, data: { user: @user } },
                 status: :ok
        else
          render json: { messages: I18n.t('signed_in_failed_unauthorized'), is_success: false, data: {} },
                 status: :unauthorized
        end
      end

      def destroy
        sign_out
        render json: { messages: I18n.t('signed_out_successfully'), is_success: true }, status: :ok
      end

      private

      def sign_in_params
        params.require(:user).permit :email, :password
      end

      def load_user
        @user = User.find_for_database_authentication(email: sign_in_params[:email])
        @user || render(json: { messages: I18n.t('cannot_get_user'), is_success: false, data: {} }, status: :not_found)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dispatches_controller.rb
# frozen_string_literal: true

class DispatchesController < ApplicationController
  def index
    @dispatches = Dispatch.includes(message: [:user]).limit(1000)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_bootstrap_views_helper.rb
module DeviseBootstrapViewsHelper
  def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |message| content_tag(:li, message) }.join
    sentence = I18n.t(
      'errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase
    )

    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="alert-heading">#{sentence}</h4>
      <ul class="mb-0">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/dispatches_helper.rb
module DispatchesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= link_to blob.filename, blob %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/dispatches/index.html.haml
- content_for :title, "Listing dispatches"

%table.table
  %thead
    %tr
      %th User
      %th Message
      %th Phone
      %th Messenger type
      %th Send at
      %th Status

  %tbody
    - @dispatches.each do |dispatch|
      %tr
        %td
          = dispatch.message.user.email
        %td
          = dispatch.message.id
          .text-muted.small= dispatch.message.body
        %td= dispatch.phone
        %td= dispatch.messenger_type
        %td= l(dispatch.send_at||dispatch.created_at, format: :short)
        %td= dispatch.status

app/views/home/index.html.haml
- content_for :title, "Отправка сообщений в популярные мессенджеры"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %title Nanoservice
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      .row
        = render partial: 'shared/navbar'
    .container
      .row
        .col-md-12
          %h1= yield :title
          = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %title Nanoservice
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      .row
        = render partial: 'shared/navbar'
    .container
      .row
        .col-12
          .card.card-body.shadow-lg
            = yield

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-5
  .container-fluid
    %button.navbar-toggler{"aria-controls" => "navbarTogglerMain", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerMain", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    = link_to t('nanoservice'), root_path, class: 'navbar-brand'
    #navbarTogglerMain.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.mb-2.mb-lg-0
        %li.nav-item
          = link_to t('home'), root_path, class: ['nav-link', ('active' if current_page?(root_path))]

      %ul.navbar-nav.ml-auto.mb-2.mb-lg-0
        - if user_signed_in?
          %li.nav-item
            = link_to t('account'), edit_user_registration_path, class: ['nav-link', ('active' if current_page?(edit_user_registration_path))]
          - if current_user.admin?
            %li.nav-item
              = link_to t('dispatches'), dispatches_path, class: ['nav-link', ('active' if controller_name == 'dispatches')]
            %li.nav-item
              = link_to t('sidekiq'), sidekiq_web_path, target: '_blank', class: 'nav-link'
          %li.nav-item
            = link_to t('logout'), destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            = link_to t('sign_up'), new_user_registration_path, class: ['nav-link', ('active' if current_page?(new_user_registration_path))]
          %li.nav-item
            = link_to t('login'), new_user_session_path, class: ['nav-link', ('active' if current_page?(new_user_session_path))]